# Generated by Django 3.2.12 on 2024-03-11 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NithClothingApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='size',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
