# Generated by Django 3.2.12 on 2023-12-23 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NithClothingApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='productsize',
            field=models.CharField(max_length=255),
        ),
    ]
