# Generated by Django 3.2.12 on 2023-12-27 13:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NithClothingApp', '0003_auto_20231226_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_drop_link',
            name='DateTime',
            field=models.DateField(default=datetime.date(2023, 12, 27)),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('zipcode', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='NithClothingApp.user')),
            ],
        ),
    ]
