# Generated by Django 3.2.12 on 2023-12-27 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NithClothingApp', '0004_auto_20231227_1348'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
