# Generated by Django 3.2.12 on 2024-03-13 12:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NithClothingApp', '0007_trackingdetails_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=255)),
                ('lname', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('zipcode', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='trackinglink',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='trackingno',
        ),
        migrations.AlterField(
            model_name='admin_drop_link',
            name='DateTime',
            field=models.DateField(default=datetime.date(2024, 3, 13)),
        ),
        migrations.DeleteModel(
            name='TrackingDetails',
        ),
    ]
