# Generated by Django 3.2.12 on 2024-01-01 14:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NithClothingApp', '0007_alter_cart_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='trackinglink',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='admin_drop_link',
            name='DateTime',
            field=models.DateField(default=datetime.date(2024, 1, 1)),
        ),
    ]
