# Generated by Django 3.2.12 on 2024-01-01 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NithClothingApp', '0008_auto_20240101_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='totalprice',
            field=models.FloatField(null=True),
        ),
    ]
