# Generated by Django 3.2.12 on 2024-03-15 14:15

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('NithClothingApp', '0008_auto_20240313_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_drop_link',
            name='DropDate',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='admin_drop_link',
            name='DateTime',
            field=models.DateField(default=datetime.date(2024, 3, 15)),
        ),
    ]
