# Generated by Django 3.2.12 on 2024-02-02 16:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NithClothingApp', '0009_alter_order_totalprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_drop_link',
            name='DateTime',
            field=models.DateField(default=datetime.date(2024, 2, 2)),
        ),
        migrations.AlterField(
            model_name='order',
            name='totalprice',
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name='TrackingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trackingno', models.CharField(max_length=255, null=True)),
                ('trackinglink', models.CharField(max_length=255, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NithClothingApp.order')),
            ],
        ),
    ]
